### ISSUE TITLE
Running games in parallel

### ISSUE THREAD

**Issue by trentzz** [trentzz/checkers-board-tournament#15]
Add options to run games and rounds in parallel to speed up runtime.

**Comment by donren-leung** [comment]
Games within a round yes, rounds in parallel probably not - I'm experimenting with a variable K-factor (adjustment rate) for Elo, since there is such a large discrepancy between the starting ratings (all 1500) and actual performance rating, this is better for faster convergence.

And it's better to use more up-to-date ratings than assuming 1500 all the way (compare running all the rounds in one big tournament, and calculating ratings from the results as a single batch VS multiple double-round-robin tournaments where ratings get updated after each tourney)

So there are two main options - 
- (1) Process all games requested by user, irrespective of round, then retroactively calculate the rating looking at R1 results, then R2 results, and so on -- all games can be computed simultaneously/in any order.
- (2) Process games round by round, then after each round (mini-tourney), update the rating -- games within a round can be computed simultaneously/in any order

- The drawback of (1) is you can't support tournament schedules based on performance so far in the tournament (like Swiss) if we wanna implement that in the future, whereas after (2) (where rounds might be 1 game/player instead of round-robin) you can draw up the next schedule

Also, we can consider manually giving bots that we have benchmarked some starting rating closer to their measured performance.
